version: '3.8'
services:
  certificados-app:
    image: ethos-monorepo
    env_file:
      - ./apps/.env
      - ./apps/certificados-cat/.env
    environment:
      - APP_NAME=certificados-cat # Nome da aplicação para certificados
    ports:
      - "3000:3000" # Porta padrão, ajuste se necessário
    # Adicione outras configurações como volumes, redes, etc., se necessário
