version: "3.8"

x-network-backend: &network-backend
  networks:
    - backend-network

x-extra_hosts-planejador: &extra_hosts-planejador
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-extra_hosts-user-auth: &extra_hosts-user-auth
  extra_hosts:
    - "cerberus:192.168.99.109"
    - "ubiquiti:192.168.99.102"

services:
  user-auth:
    container_name: user-auth
    # Imagem específica gerada pelo CI/CD para o app 'user-authenticator'
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:user-authenticator-latest
    restart: always
    ports:
      - "30002:30002"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=30002

      # Syneco DB (SQL Server)
      - SQLHOST=${SQLHOST}
      - SQLUSER=${SQLUSER}
      - SQLSENHA=${SQLSENHA}
      - SQLDATABASE=${SQLDATABASE}
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      # Auth
      - SECRET=${SECRET}
      - EXPIREHOURS=${EXPIREHOURS}

      # App Mode
      - APP_MODE=${APP_MODE}
    <<: [*network-backend, *extra_hosts-user-auth]

  app-route:
    container_name: app-route
    # Imagem específica para 'app-ethos'
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:app-ethos-latest
    restart: always
    ports:
      - "30005:30005"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=30005

      # Mongo DB
      - MONGOHOST=${MONGOHOST}
      - MONGOUSER=${MONGOUSER}
      - MONGOPASSWORD=${MONGOPASSWORD}
      - MONGODATABASE=${MONGODATABASE}

      # Auth
      - SECRET=${SECRET}
      - EXPIREHOURS=${EXPIREHOURS}

      # App Mode
      - APP_MODE=${APP_MODE}
    <<: [*network-backend]

  planejador-api:
    container_name: planejador-api
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:planejador-latest
    restart: always
    ports:
      - "30006:30006"
    environment:
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - NODE_ENV=production
      - PORT=30006
      - SQLHOST=${SQLHOST}
      - SQLUSER=${SQLUSER}
      - SQLSENHA=${SQLSENHA}
      - SQLDATABASE=${SQLDATABASE}
      - SQLPORT=${SQLPORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SECRET=${SECRET}
      - EXPIREHOURS=${EXPIREHOURS}
      - APP_MODE=${APP_MODE}
      - TZ=${TZ}
      - CHECKPOINT_RANGE=${CHECKPOINT_RANGE}
      - BATELADAMAX=${BATELADAMAX}
      - PINTURAMAX=${PINTURAMAX}
      - ORACLEHOST=${ORACLEHOST}
      - ORACLEPORT=${ORACLEPORT}
      - ORACLEUSER=${ORACLEUSER}
      - ORACLEPASSWORD=${ORACLEPASSWORD}
      - ORACLESID=${ORACLESID}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - ESTRUTURA_SERVICE_URL=${ESTRUTURA_SERVICE_URL}
      - SYSTEM_USER_ID=${SYSTEM_USER_ID}
    <<: [*network-backend, *extra_hosts-planejador]

  planejador-master:
    container_name: planejador-master
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:planejador-importador-latest
    restart: always
    environment:
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - NODE_ENV=production
      - HOST=${HOST}
      - APP_ENTRY_FILE=main.importador.js
      - SQLHOST=${SQLHOST}
      - SQLUSER=${SQLUSER}
      - SQLSENHA=${SQLSENHA}
      - SQLDATABASE=${SQLDATABASE}
      - SQLPORT=${SQLPORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SECRET=${SECRET}
      - EXPIREHOURS=${EXPIREHOURS}
      - APP_MODE=${APP_MODE}
      - TZ=${TZ}
      - CHECKPOINT_RANGE=${CHECKPOINT_RANGE}
      - BATELADAMAX=${BATELADAMAX}
      - PINTURAMAX=${PINTURAMAX}
      - ORACLEHOST=${ORACLEHOST}
      - ORACLEPORT=${ORACLEPORT}
      - ORACLEUSER=${ORACLEUSER}
      - ORACLEPASSWORD=${ORACLEPASSWORD}
      - ORACLESID=${ORACLESID}
      - REDIS_PORT=${REDIS_PORT}
      - ESTRUTURA_SERVICE_URL=${ESTRUTURA_SERVICE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - SYSTEM_USER_ID=${SYSTEM_USER_ID}
    <<: [*network-backend, *extra_hosts-planejador]

  planejador-worker:
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:planejador-worker-latest
    restart: always
    deploy:
      replicas: 2
    environment:
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - NODE_ENV=production
      - HOST=${HOST}
      - APP_ENTRY_FILE=main.worker.js
      - SQLHOST=${SQLHOST}
      - SQLUSER=${SQLUSER}
      - SQLSENHA=${SQLSENHA}
      - SQLDATABASE=${SQLDATABASE}
      - SQLPORT=${SQLPORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SECRET=${SECRET}
      - EXPIREHOURS=${EXPIREHOURS}
      - APP_MODE=${APP_MODE}
      - TZ=${TZ}
      - CHECKPOINT_RANGE=${CHECKPOINT_RANGE}
      - BATELADAMAX=${BATELADAMAX}
      - PINTURAMAX=${PINTURAMAX}
      - ORACLEHOST=${ORACLEHOST}
      - ORACLEPORT=${ORACLEPORT}
      - ORACLEUSER=${ORACLEUSER}
      - ORACLEPASSWORD=${ORACLEPASSWORD}
      - ORACLESID=${ORACLESID}
      - REDIS_PORT=${REDIS_PORT}
      - ESTRUTURA_SERVICE_URL=${ESTRUTURA_SERVICE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - SYSTEM_USER_ID=${SYSTEM_USER_ID}
    <<: [*network-backend, *extra_hosts-planejador]

  wifi-ethos:
    container_name: wifi-ethos
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:wifi-ethos-latest
    restart: always
    ports:
      - "30008:30008"
    environment:
      - NODE_ENV=production
      - PORT=30008
      - EMAIL_SERVICE_URL=${EMAIL_SERVICE_URL}
      - WIFI_CHECKOUT_URI=${WIFI_CHECKOUT_URI}
      - WIFI_TIME_LIMIT_MINUTES=${WIFI_TIME_LIMIT_MINUTES}
      - UBIQUITI_SERVICE_URL=${UBIQUITI_SERVICE_URL}
      - MONGOUSER=${MONGOUSER}
      - MONGOPASSWORD=${MONGOPASSWORD}
      - MONGODATABASE=${MONGODATABASE}
      - MONGOHOST=${MONGOHOST}
      - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}
      - UBIQUITI_USERNAME=${UBIQUITI_USERNAME}
      - UBIQUITI_PASSWORD=${UBIQUITI_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - WIFI_SSID=${WIFI_SSID}
    <<: [*network-backend, *extra_hosts-planejador]

  buffer-api:
    container_name: buffer-api
    image: ghcr.io/${GITHUB_USER_OR_ORG}/ethoscodespace:buffer-api-latest
    restart: always
    ports:
      - "30009:30009"
    environment:
      - NODE_ENV=production
      - PORT=30009
      - HOST=0.0.0.0
      
      # Database Configuration
      - SQLHOST=${SQLHOST}
      - SQLUSER=${SQLUSER}
      - SQLSENHA=${SQLSENHA}
      - SQLDATABASE=${SQLDATABASE}
      - SQLPORT=${SQLPORT}
      - TZ=${TZ}
      # Storage & Files
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - EXCELFILE=${EXCELFILE}

    volumes:
      # Volume CIFS/Samba
      - win_share_excel:/mnt/storage
    <<: [*network-backend, *extra_hosts-planejador]

networks:
  backend-network:
    driver: bridge

volumes:
  win_share_excel:
    driver: local
    driver_opts:
      type: cifs
      o: "username=${SMB_USER},password=${SMB_PASS},domain=${SMB_DOMAIN},vers=3.0,uid=1000,gid=1000,file_mode=0775,dir_mode=0775,noperm"
      device: "${SMB_PATH}"
